src/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

src/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.home_view, name='home'),
]

src/money-boy/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('dashboard.urls')),
]

src/account/models.py
from django.db import models

# Create your models here.

src/account/forms.py
from django import forms


class LoginForm(forms.Form):
    """Login Form to use login page
    """
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

src/account/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from .forms import LoginForm


def login_view(request):
    form = LoginForm()

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(settings.LOGIN_REDIRECT_URL)
                else:
                    return render(request, 'account/login.html', {'errors': 'error', 'form': form})
            else:
                return render(request, 'account/login.html', {'errors': 'error', 'form': form})

    return render(request, 'account/login.html', {'form': form})

src/dashboard/views.py
from django.shortcuts import render, HttpResponse
from django.contrib.auth.decorators import login_required


@login_required
def home_view(request):
    """home view
    """
    return render(request,
                  'dashboard/dashboard.html',
                  {})

src/account/templates/account_base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/account.css" %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;1,400;1,700&display=swap" rel="stylesheet">
</head>
<body>
  <div id="content" class="container">
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>

src/dashboard/templates/dashboard/card.html
{% load static %}

{% block custom_static %}
    <link rel="stylesheet" href="{% static 'css/dashboard/card.css' %}">
{% endblock custom_static %}

<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-10 col-lg-9 col-md-8 ml-auto">
                <div class="row pt-md-5 mt-md-3 mb-5">
                    <div class="col-xl-3 col-sm-6 p-2">
                        <div class="card card-common">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <i class="fas fa-shopping-cart fa-3x text-warning"></i>
                                    <div class="text-right text-secondary">
                                        <h5>Sales</h5>
                                        <h3>$135.000</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer text-secondary">
                                <i class="fas fa-sync mr-3"></i>
                                <span>Updated Now</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-sm-6 p-2">
                        <div class="card card-common">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <i class="fas fa-money-bill-alt fa-3x text-warning"></i>
                                    <div class="text-right text-success">
                                        <h5>Expense</h5>
                                        <h3>$39.000</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer text-secondary">
                                <i class="fas fa-sync mr-3"></i>
                                <span>Updated Now</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-sm-6 p-2">
                        <div class="card card-common">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <i class="fas fa-users fa-3x text-info"></i>
                                    <div class="text-right text-secondary">
                                        <h5>Users</h5>
                                        <h3>$15.000</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer text-secondary">
                                <i class="fas fa-sync mr-3"></i>
                                <span>Updated Now</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-sm-6 p-2">
                        <div class="card card-common">
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <i class="fas fa-chart-line fa-3x text-danger"></i>
                                    <div class="text-right text-secondary">
                                        <h5>Visitors</h5>
                                        <h3>$45.000</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer text-secondary">
                                <i class="fas fa-sync mr-3"></i>
                                <span>Updated Now</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

src/dashboard/templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% load static %}

{% block title %}money-boy{% endblock %}

{% block custom_static %}
    <link rel="stylesheet" href="{% static 'css/dashboard/dashboard.css' %}">
{% endblock custom_static %}

{% block content %}
    <!-- card -->
    {% include "dashboard/card.html" %}
    <!-- end of card -->
    <!-- tables -->
    {% include "dashboard/tables.html" %}
    <!-- end of tables -->
{% endblock %}


{% block custom_js %}
    <script src="{% static 'js/src/dashboard/dashboard.js' %}"></script>

    <script>
    </script>
{% endblock custom_js %}

src/dashboard/templates/dashboard/pagenation.html
<nav>
    <ul class="pagination justify-content-center">
        <li class="page-item active">
            <a href="#" class="page-link py-2 px-3">
                <span>{{previous}}</span>
            </a>
        </li>
        <li class="page-item">
            <a href="#" class="page-link py-2 px-3">
                1
            </a>
        </li>
        <li class="page-item">
            <a href="#" class="page-link py-2 px-3">
                2
            </a>
        </li>
        <li class="page-item">
            <a href="#" class="page-link py-2 px-3">
                3
            </a>
        </li>
        <li class="page-item">
            <a href="#" class="page-link py-2 px-3">
                <span>{{next}}</span>
            </a>
        </li>
    </ul>
</nav>

src/dashboard/templates/dashboard/tables.html
{% load static %}

{% block custom_static %}
    <link rel="stylesheet" href="{% static 'css/dashboard/tables.css' %}">
{% endblock custom_static %}

<section>
    <div class="container-fluid">
        <div class="row mb-5">
            <div class="col-xl-10 col-lg-9 col-md-8 ml-auto">
                <div class="row">
                    <div class="col-xl-6 col-12 mb-4">
                        <h3 class="text-muted text-center mb-3">Staff Salary</h3>
                        <table class="table bg-light text-center">
                            <thead>
                                <tr class="text-muted">
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Salary</th>
                                    <th>Date</th>
                                    <th>Contact</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>1</th>
                                    <td>John</td>
                                    <td>$2000</td>
                                    <td>25/05/2020</td>
                                    <td>
                                        <button 
                                          type="button"
                                          class="btn btn-info btn-sm"
                                        >
                                          Message
                                        </button>
                                    </td>
                                </tr>
                                <tr>
                                    <th>2</th>
                                    <td>Ann</td>
                                    <td>$2000</td>
                                    <td>25/05/2020</td>
                                    <td>
                                        <button 
                                          type="button"
                                          class="btn btn-info btn-sm"
                                        >
                                          Message
                                        </button>
                                    </td>
                                </tr>
                                <tr>
                                    <th>3</th>
                                    <td>Mark</td>
                                    <td>$2000</td>
                                    <td>25/05/2020</td>
                                    <td>
                                        <button 
                                          type="button"
                                          class="btn btn-info btn-sm"
                                        >
                                          Message
                                        </button>
                                    </td>
                                </tr>
                                <tr>
                                    <th>4</th>
                                    <td>Mary</td>
                                    <td>$2000</td>
                                    <td>25/05/2020</td>
                                    <td>
                                        <button 
                                          type="button"
                                          class="btn btn-info btn-sm"
                                        >
                                          Message
                                        </button>
                                    </td>
                                </tr>
                                <tr>
                                    <th>5</th>
                                    <td>Bob</td>
                                    <td>$2000</td>
                                    <td>25/05/2020</td>
                                    <td>
                                        <button 
                                          type="button"
                                          class="btn btn-info btn-sm"
                                        >
                                          Message
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <!-- pagenation -->
                        <!-- https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#include -->
                        {% include "dashboard/pagenation.html" with previous="&laquo;" next="&raquo;"%}
                        <!-- end of pagenation -->
                    </div>
                    <div class="col-xl-6 col-12">
                        <h3 class="text-muted text-center mb-3">Recent Payments</h3>
                        <table class="table table-dark table-hover text-center">
                            <thead>
                                <tr class="text-muted">
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Price</th>
                                    <th>Date</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>1</th>
                                    <td>Monica</td>
                                    <td>$2000</td>
                                    <td>25/05/2020</td>
                                    <td>
                                        <span class="badge badge-success w-75 py-2">
                                            Approved
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>2</th>
                                    <td>Nick</td>
                                    <td>$2000</td>
                                    <td>25/05/2020</td>
                                    <td>
                                        <span class="badge badge-success w-75 py-2">
                                            Approved
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>3</th>
                                    <td>Alex</td>
                                    <td>$2000</td>
                                    <td>25/05/2020</td>
                                    <td>
                                        <span class="badge badge-danger w-75 py-2">
                                            Pending
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>4</th>
                                    <td>Jane</td>
                                    <td>$2000</td>
                                    <td>25/05/2020</td>
                                    <td>
                                        <span class="badge badge-danger w-75 py-2">
                                            Pending
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <th>5</th>
                                    <td>Michael</td>
                                    <td>$2000</td>
                                    <td>25/05/2020</td>
                                    <td>
                                        <span class="badge badge-success w-75 py-2">
                                            Approved
                                        </span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <!-- pagenation -->
                        {% include "dashboard/pagenation.html" with previous="Previous" next="Next" %}
                        <!-- end of pagenation -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

src/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<link rel="title icon" type="image/png" href="{% static 'img/title-img.png' %}"/>-->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <!-- fontawesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js" integrity="sha384-xymdQtn1n3lH2wcu0qhcdaOpQwyoarkgLVxC/wZ5q7h9gHtxICrpcaSUfygqZGOe" crossorigin="anonymous"></script>
    <!-- highlight.js https://highlightjs.org/download/ -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/railscasts.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js"></script>
    {% block custom_static %}{% endblock custom_static %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>

    <!-- navbar -->
    {% include 'navbar.html' %}
    <!-- end of navbar -->

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
    {% block custom_js %}{% endblock custom_js %}
</body>
</html>

src/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-light">
  <button 
    class="navbar-toggler ml-auto mb-2 bg-light"
    type="button"
    data-toggle="collapse"
    data-target="#myNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="myNavbar">
    <div class="container-fluid">
      <div class="row">
        <!-- sidebar -->
        {% include 'sidebar.html' %}
        <!-- end of sidebar -->
        <!-- top-nav -->
        {% include 'top-nav.html' %}
        <!-- end of top-nav -->
      </div>
    </div>
  </div>
</nav>

<!-- sign out modal -->
{% include 'signout-modal.html' %}
<!-- end of sign out modal -->

src/templates/sidebar.html
{% load static %}

{% block custom_static %}
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
{% endblock custom_static %}

<div class="col-xl-2 col-lg-3 col-md-4 sidebar fixed-top">
    <a 
      href="#"
      class="
        navbar-brand
        text-white
        d-block
        mx-auto
        text-center
        py-3
        mb-4
        bottom-border"
    >Money-Boy
    </a>
    <div class="bottom-border pb-3">
        <img 
          src="{% static 'img/admin.jpeg' %}"
          width="50"
          class="rounded-circle mr-3"
        >
        <a href="#" class="text-white">Self Note</a>
    </div>
    <ul class="navbar-nav flex-column mt-4">
        <li class="nav-item">
            <a href="#" class="nav-link text-white p-3 mb-2 current">
                <i class="fas fa-home text-light fa-lg mr-3"></i>Dashboard
            </a>
        </li>
        <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#reversing-admin-urls -->
        <li class="nav-item">
            <a href="{% url 'admin:auth_user_changelist'%}" class="nav-link text-white p-3 mb-2 sidebar-link">
                <i class="fas fa-user text-light fa-lg mr-3"></i>Profile
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link text-white p-3 mb-2 sidebar-link">
                <i class="fas fa-envelope text-light fa-lg mr-3"></i>Inbox
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link text-white p-3 mb-2 sidebar-link">
                <i class="fas fa-shopping-cart text-light fa-lg mr-3"></i>Sales
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link text-white p-3 mb-2 sidebar-link">
                <i class="fas fa-chart-line text-light fa-lg mr-3"></i>Analytics
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link text-white p-3 mb-2 sidebar-link">
                <i class="fas fa-chart-bar text-light fa-lg mr-3"></i>Chart
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link text-white p-3 mb-2 sidebar-link">
                <i class="fas fa-table text-light fa-lg mr-3"></i>Tables
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link text-white p-3 mb-2 sidebar-link">
                <i class="fas fa-wrench text-light fa-lg mr-3"></i>Settings
            </a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link text-white p-3 mb-2 sidebar-link">
                <i class="fas fa-file-alt text-light fa-lg mr-3"></i>Documentation
            </a>
        </li>
    </ul>
</div>

src/templates/signout-modal.html
<div class="modal fade" id="sign-out">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Want to leave?</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                Press logout to leave
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">Stay Here</button>
                <a href="{% url 'account:logout' %}" class="btn btn-danger">Logout</a>
            </div>
        </div>
    </div>
</div>

src/templates/top-nav.html
{% load static %}

{% block custom_static %}
    <link rel="stylesheet" href="{% static 'css/top-nav.css' %}">
{% endblock custom_static %}

<div class="col-xl-10 col-lg-9 col-md-8 ml-auto bg-dark fixed-top py-2 top-navbar">
    <div class="row align-items-center">
        <div class="col-md-4">
            <h4 class="text-light text-uppercase mb-0">Dashboard</h4>
        </div>
        <div class="col-md-5">
            <form>
                <div class="input-group">
                    <input type="text"
                           class="form-control search-input text-white"
                           placeholder="Search...">
                    <button type="button" 
                            class="btn btn-white search-button">
                        <i class="fas fa-search text-danger"></i>
                    </button>
                </div>
            </form>
        </div>
        <div class="col-md-3">
            <ul class="navbar-nav">
                <li class="nav-item icon-parent">
                    <a href="#" class="nav-link icon-bullet">
                        <i class="fas fa-comments text-muted fa-lg"></i>
                    </a>
                </li>
                <li class="nav-item icon-parent">
                    <a href="#" class="nav-link icon-bullet">
                        <i class="fas fa-bell text-muted fa-lg"></i>
                    </a>
                </li>
                <li class="nav-item ml-md-auto">
                    <!-- https://cccabinet.jpn.org/bootstrap4/javascript/tooltips/options -->
                    <a href="{% url 'account:logout' %}" 
                      class="nav-link" 
                      data-toggle="modal"
                      data-target="#sign-out"
                      data-backdrop="false"
                    >
                      <i class="fas fa-sign-out-alt text-danger fa-lg"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>